/// <reference types='./globals.d.ts' />
/* tslint:disable */
/* eslint-disable */
/**
 * soybean-admin-go - version 1.0.0
 *
 *
 *
 * OpenAPI version: 3.1.0
 *
 *
 * NOTE: This file is auto generated by the alova's vscode plugin.
 *
 * https://alova.js.org/devtools/vscode
 *
 * **Do not edit the file manually.**
 */
export default {
  'general.get_auth_getuserinfo': ['GET', '/auth/getUserInfo'],
  'general.post_auth_login': ['POST', '/auth/login'],
  'general.post_auth_refreshtoken': ['POST', '/auth/refreshToken'],
  'general.get_buttons': ['GET', '/buttons'],
  'general.post_buttons': ['POST', '/buttons'],
  'general.post_buttons_batchdelete': ['POST', '/buttons/batchDelete'],
  'general.post_buttons_delete': ['POST', '/buttons/delete'],
  'general.get_buttons_role': ['GET', '/buttons/role'],
  'general.post_buttons_update': ['POST', '/buttons/update'],
  'general.get_buttons_user': ['GET', '/buttons/user'],
  'general.get_menus': ['GET', '/menus'],
  'general.post_menus': ['POST', '/menus'],
  'general.post_menus_batchdelete': ['POST', '/menus/batchDelete'],
  'general.get_menus_constant': ['GET', '/menus/constant'],
  'general.post_menus_delete': ['POST', '/menus/delete'],
  'general.get_menus_role': ['GET', '/menus/role'],
  'general.post_menus_update': ['POST', '/menus/update'],
  'general.get_menus_user': ['GET', '/menus/user'],
  'general.get_roles': ['GET', '/roles'],
  'general.post_roles': ['POST', '/roles'],
  'general.get_roles_all': ['GET', '/roles/all'],
  'general.post_roles_batchdelete': ['POST', '/roles/batchDelete'],
  'general.post_roles_buttons': ['POST', '/roles/buttons'],
  'general.post_roles_delete': ['POST', '/roles/delete'],
  'general.post_roles_menus': ['POST', '/roles/menus'],
  'general.post_roles_update': ['POST', '/roles/update'],
  'general.get_users': ['GET', '/users'],
  'general.post_users': ['POST', '/users'],
  'general.post_users_batchdelete': ['POST', '/users/batchDelete'],
  'general.get_users_checkusername': ['GET', '/users/checkUsername'],
  'general.post_users_delete': ['POST', '/users/delete'],
  'general.post_users_password': ['POST', '/users/password'],
  'general.get_users_roles': ['GET', '/users/roles'],
  'general.post_users_roles': ['POST', '/users/roles']
};
