/* tslint:disable */
/* eslint-disable */
/**
 * soybean-admin-go - version 1.0.0
 *
 *
 *
 * OpenAPI version: 3.1.0
 *
 *
 * NOTE: This file is auto generated by the alova's vscode plugin.
 *
 * https://alova.js.org/devtools/vscode
 *
 * **Do not edit the file manually.**
 */
import type { Alova, AlovaMethodCreateConfig, AlovaGenerics, Method } from 'alova';
import type { $$userConfigMap, alovaInstance } from '.';
import type apiDefinitions from './apiDefinitions';

type CollapsedAlova = typeof alovaInstance;
type UserMethodConfigMap = typeof $$userConfigMap;

type Alova2MethodConfig<Responded> =
  CollapsedAlova extends Alova<
    AlovaGenerics<
      any,
      any,
      infer RequestConfig,
      infer Response,
      infer ResponseHeader,
      infer L1Cache,
      infer L2Cache,
      infer SE
    >
  >
    ? Omit<
        AlovaMethodCreateConfig<
          AlovaGenerics<Responded, any, RequestConfig, Response, ResponseHeader, L1Cache, L2Cache, SE>,
          any,
          Responded
        >,
        'params'
      >
    : never;

// Extract the return type of transform function that define in $$userConfigMap, if it not exists, use the default type.
type ExtractUserDefinedTransformed<
  DefinitionKey extends keyof typeof apiDefinitions,
  Default
> = DefinitionKey extends keyof UserMethodConfigMap
  ? UserMethodConfigMap[DefinitionKey]['transform'] extends (...args: any[]) => any
    ? Awaited<ReturnType<UserMethodConfigMap[DefinitionKey]['transform']>>
    : Default
  : Default;
type Alova2Method<
  Responded,
  DefinitionKey extends keyof typeof apiDefinitions,
  CurrentConfig extends Alova2MethodConfig<any>
> =
  CollapsedAlova extends Alova<
    AlovaGenerics<
      any,
      any,
      infer RequestConfig,
      infer Response,
      infer ResponseHeader,
      infer L1Cache,
      infer L2Cache,
      infer SE
    >
  >
    ? Method<
        AlovaGenerics<
          CurrentConfig extends undefined
            ? ExtractUserDefinedTransformed<DefinitionKey, Responded>
            : CurrentConfig['transform'] extends (...args: any[]) => any
              ? Awaited<ReturnType<CurrentConfig['transform']>>
              : ExtractUserDefinedTransformed<DefinitionKey, Responded>,
          any,
          RequestConfig,
          Response,
          ResponseHeader,
          L1Cache,
          L2Cache,
          SE
        >
      >
    : never;

export type System_userdto = {
  buttons?: string[];
  createTime?: string;
  id?: number;
  roles?: string[];
  updateTime?: string;
  userName?: string;
};
export type Utils_response_system_userdto = {
  /**
   * [required]
   */
  code: string;
  /**
   * [required]
   */
  data: System_userdto;
  /**
   * [required]
   */
  msg: string;
};
export type System_token = {
  /**
   * [required]
   */
  refreshToken: string;
  /**
   * [required]
   */
  token: string;
};
export type Utils_response_system_token = {
  /**
   * [required]
   */
  code: string;
  /**
   * [required]
   */
  data: System_token;
  /**
   * [required]
   */
  msg: string;
};
export type System_button = {
  code?: string;
  createTime?: string;
  desc?: string;
  id?: number;
  updateTime?: string;
};
export type Utils_response_array_system_button = {
  /**
   * [required]
   */
  code: string;
  /**
   * [required]
   */
  data: System_button[];
  /**
   * [required]
   */
  msg: string;
};
export type Utils_response_system_button = {
  /**
   * [required]
   */
  code: string;
  /**
   * [required]
   */
  data: System_button;
  /**
   * [required]
   */
  msg: string;
};
export type Utils_response_string = {
  /**
   * [required]
   */
  code: string;
  /**
   * [required]
   */
  data: string;
  /**
   * [required]
   */
  msg: string;
};
export type System_menuquery = {
  id?: number;
  key?: string;
  menuId?: number;
  value?: string;
};
export type System_menu = {
  /**
   * 激活的菜单名
   */
  activeMenu?: string;
  buttons?: System_button[];
  children?: System_menu[];
  component?: string;
  constant?: boolean;
  createTime?: string;
  fixedIndexInTab?: number;
  /**
   * 是否隐藏菜单
   */
  hideInMenu?: boolean;
  href?: string;
  /**
   * [required]
   */
  i18nKey: string;
  icon?: string;
  /**
   * [required]
   */
  iconType: string;
  id?: number;
  keepAlive?: boolean;
  localIcon?: string;
  /**
   * [required]
   */
  menuName: string;
  /**
   * [required]
   */
  menuType: string;
  /**
   * 是否支持多标签
   */
  multiTab?: boolean;
  order?: number;
  /**
   * 父菜单ID
   */
  parentId?: number;
  query?: System_menuquery[];
  /**
   * [required]
   */
  routeName: string;
  /**
   * [required]
   */
  routePath: string;
  status?: string;
  updateTime?: string;
};
export type Utils_response_array_system_menu = {
  /**
   * [required]
   */
  code: string;
  /**
   * [required]
   */
  data: System_menu[];
  /**
   * [required]
   */
  msg: string;
};
export type System_role = {
  buttons?: System_button[];
  createTime?: string;
  id?: number;
  menu?: System_menu[];
  roleDesc?: string;
  roleName?: string;
  updateTime?: string;
};
export type Utils_pagination_system_role = {
  /**
   * [required]
   */
  current: number;
  /**
   * [required]
   */
  records: System_role[];
  /**
   * [required]
   */
  size: number;
  /**
   * [required]
   */
  total: number;
};
export type Utils_response_utils_pagination_system_role = {
  /**
   * [required]
   */
  code: string;
  /**
   * [required]
   */
  data: Utils_pagination_system_role;
  /**
   * [required]
   */
  msg: string;
};
export type Utils_response_system_role = {
  /**
   * [required]
   */
  code: string;
  /**
   * [required]
   */
  data: System_role;
  /**
   * [required]
   */
  msg: string;
};
export type Utils_response_array_system_role = {
  /**
   * [required]
   */
  code: string;
  /**
   * [required]
   */
  data: System_role[];
  /**
   * [required]
   */
  msg: string;
};
export type System_user = {
  createTime?: string;
  id?: number;
  password?: string;
  roles?: System_role[];
  updateTime?: string;
  userName?: string;
};
export type Utils_pagination_system_user = {
  /**
   * [required]
   */
  current: number;
  /**
   * [required]
   */
  records: System_user[];
  /**
   * [required]
   */
  size: number;
  /**
   * [required]
   */
  total: number;
};
export type Utils_response_utils_pagination_system_user = {
  /**
   * [required]
   */
  code: string;
  /**
   * [required]
   */
  data: Utils_pagination_system_user;
  /**
   * [required]
   */
  msg: string;
};
export type Utils_response_system_user = {
  /**
   * [required]
   */
  code: string;
  /**
   * [required]
   */
  data: System_user;
  /**
   * [required]
   */
  msg: string;
};
export type Utils_existsresult = {
  exists?: boolean;
};
export type Utils_response_utils_existsresult = {
  /**
   * [required]
   */
  code: string;
  /**
   * [required]
   */
  data: Utils_existsresult;
  /**
   * [required]
   */
  msg: string;
};
declare global {
  interface Apis {
    general: {
      /**
       * ---
       *
       * [GET] 获取用户信息
       *
       * **path:** /auth/getUserInfo
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = {
       *   // [required]
       *   code: string
       *   // [required]
       *   data: {
       *     buttons?: string[]
       *     createTime?: string
       *     id?: number
       *     roles?: string[]
       *     updateTime?: string
       *     userName?: string
       *   }
       *   // [required]
       *   msg: string
       * }
       * ```
       */
      get_auth_getuserinfo<Config extends Alova2MethodConfig<Utils_response_system_userdto>>(
        config?: Config
      ): Alova2Method<Utils_response_system_userdto, 'general.get_auth_getuserinfo', Config>;
      /**
       * ---
       *
       * [POST] 用户登录
       *
       * **path:** /auth/login
       *
       * ---
       *
       * **RequestBody**
       * ```ts
       * type RequestBody = {
       *   password?: string
       *   userName?: string
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = {
       *   // [required]
       *   code: string
       *   // [required]
       *   data: {
       *     // [required]
       *     refreshToken: string
       *     // [required]
       *     token: string
       *   }
       *   // [required]
       *   msg: string
       * }
       * ```
       */
      post_auth_login<
        Config extends Alova2MethodConfig<Utils_response_system_token> & {
          data: {
            password?: string;
            userName?: string;
          };
        }
      >(
        config: Config
      ): Alova2Method<Utils_response_system_token, 'general.post_auth_login', Config>;
      /**
       * ---
       *
       * [POST] 刷新Token
       *
       * **path:** /auth/refreshToken
       *
       * ---
       *
       * **RequestBody**
       * ```ts
       * type RequestBody = {
       *   refreshToken?: string
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = {
       *   // [required]
       *   code: string
       *   // [required]
       *   data: {
       *     // [required]
       *     refreshToken: string
       *     // [required]
       *     token: string
       *   }
       *   // [required]
       *   msg: string
       * }
       * ```
       */
      post_auth_refreshtoken<
        Config extends Alova2MethodConfig<Utils_response_system_token> & {
          data: {
            refreshToken?: string;
          };
        }
      >(
        config: Config
      ): Alova2Method<Utils_response_system_token, 'general.post_auth_refreshtoken', Config>;
      /**
       * ---
       *
       * [GET] 获取所有按钮
       *
       * **path:** /buttons
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = {
       *   // [required]
       *   code: string
       *   // [required]
       *   data: Array<{
       *     code?: string
       *     createTime?: string
       *     desc?: string
       *     id?: number
       *     updateTime?: string
       *   }>
       *   // [required]
       *   msg: string
       * }
       * ```
       */
      get_buttons<Config extends Alova2MethodConfig<Utils_response_array_system_button>>(
        config?: Config
      ): Alova2Method<Utils_response_array_system_button, 'general.get_buttons', Config>;
      /**
       * ---
       *
       * [POST] 创建按钮
       *
       * **path:** /buttons
       *
       * ---
       *
       * **RequestBody**
       * ```ts
       * type RequestBody = {
       *   code?: string
       *   createTime?: string
       *   desc?: string
       *   id?: number
       *   updateTime?: string
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = {
       *   // [required]
       *   code: string
       *   // [required]
       *   data: {
       *     code?: string
       *     createTime?: string
       *     desc?: string
       *     id?: number
       *     updateTime?: string
       *   }
       *   // [required]
       *   msg: string
       * }
       * ```
       */
      post_buttons<
        Config extends Alova2MethodConfig<Utils_response_system_button> & {
          data: System_button;
        }
      >(
        config: Config
      ): Alova2Method<Utils_response_system_button, 'general.post_buttons', Config>;
      /**
       * ---
       *
       * [POST] 批量删除按钮
       *
       * **path:** /buttons/batchDelete
       *
       * ---
       *
       * **RequestBody**
       * ```ts
       * type RequestBody = {
       *   ids?: number[]
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = {
       *   // [required]
       *   code: string
       *   // [required]
       *   data: string
       *   // [required]
       *   msg: string
       * }
       * ```
       */
      post_buttons_batchdelete<
        Config extends Alova2MethodConfig<Utils_response_string> & {
          data: {
            ids?: number[];
          };
        }
      >(
        config: Config
      ): Alova2Method<Utils_response_string, 'general.post_buttons_batchdelete', Config>;
      /**
       * ---
       *
       * [POST] 删除按钮
       *
       * **path:** /buttons/delete
       *
       * ---
       *
       * **RequestBody**
       * ```ts
       * type RequestBody = {
       *   id?: number
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = {
       *   // [required]
       *   code: string
       *   // [required]
       *   data: string
       *   // [required]
       *   msg: string
       * }
       * ```
       */
      post_buttons_delete<
        Config extends Alova2MethodConfig<Utils_response_string> & {
          data: {
            id?: number;
          };
        }
      >(
        config: Config
      ): Alova2Method<Utils_response_string, 'general.post_buttons_delete', Config>;
      /**
       * ---
       *
       * [GET] 获取角色按钮
       *
       * **path:** /buttons/role
       *
       * ---
       *
       * **Query Parameters**
       * ```ts
       * type QueryParameters = {
       *   // 角色ID
       *   // [required]
       *   roleId: number
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = {
       *   // [required]
       *   code: string
       *   // [required]
       *   data: Array<{
       *     code?: string
       *     createTime?: string
       *     desc?: string
       *     id?: number
       *     updateTime?: string
       *   }>
       *   // [required]
       *   msg: string
       * }
       * ```
       */
      get_buttons_role<
        Config extends Alova2MethodConfig<Utils_response_array_system_button> & {
          params: {
            /**
             * 角色ID
             * [required]
             */
            roleId: number;
          };
        }
      >(
        config: Config
      ): Alova2Method<Utils_response_array_system_button, 'general.get_buttons_role', Config>;
      /**
       * ---
       *
       * [POST] 更新按钮
       *
       * **path:** /buttons/update
       *
       * ---
       *
       * **RequestBody**
       * ```ts
       * type RequestBody = {
       *   code?: string
       *   createTime?: string
       *   desc?: string
       *   id?: number
       *   updateTime?: string
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = {
       *   // [required]
       *   code: string
       *   // [required]
       *   data: string
       *   // [required]
       *   msg: string
       * }
       * ```
       */
      post_buttons_update<
        Config extends Alova2MethodConfig<Utils_response_string> & {
          data: System_button;
        }
      >(
        config: Config
      ): Alova2Method<Utils_response_string, 'general.post_buttons_update', Config>;
      /**
       * ---
       *
       * [GET] 获取用户按钮
       *
       * **path:** /buttons/user
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = {
       *   // [required]
       *   code: string
       *   // [required]
       *   data: Array<{
       *     code?: string
       *     createTime?: string
       *     desc?: string
       *     id?: number
       *     updateTime?: string
       *   }>
       *   // [required]
       *   msg: string
       * }
       * ```
       */
      get_buttons_user<Config extends Alova2MethodConfig<Utils_response_array_system_button>>(
        config?: Config
      ): Alova2Method<Utils_response_array_system_button, 'general.get_buttons_user', Config>;
      /**
       * ---
       *
       * [GET] 获取所有菜单
       *
       * **path:** /menus
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = {
       *   // [required]
       *   code: string
       *   // [required]
       *   data: Array<{
       *     // 激活的菜单名
       *     activeMenu?: string
       *     buttons?: Array<{
       *       code?: string
       *       createTime?: string
       *       desc?: string
       *       id?: number
       *       updateTime?: string
       *     }>
       *     children?: Array<System_menu>
       *     component?: string
       *     constant?: boolean
       *     createTime?: string
       *     fixedIndexInTab?: number
       *     // 是否隐藏菜单
       *     hideInMenu?: boolean
       *     href?: string
       *     // [required]
       *     i18nKey: string
       *     icon?: string
       *     // [required]
       *     iconType: string
       *     id?: number
       *     keepAlive?: boolean
       *     localIcon?: string
       *     // [required]
       *     menuName: string
       *     // [required]
       *     menuType: string
       *     // 是否支持多标签
       *     multiTab?: boolean
       *     order?: number
       *     // 父菜单ID
       *     parentId?: number
       *     query?: Array<{
       *       id?: number
       *       key?: string
       *       menuId?: number
       *       value?: string
       *     }>
       *     // [required]
       *     routeName: string
       *     // [required]
       *     routePath: string
       *     status?: string
       *     updateTime?: string
       *   }>
       *   // [required]
       *   msg: string
       * }
       * ```
       */
      get_menus<Config extends Alova2MethodConfig<Utils_response_array_system_menu>>(
        config?: Config
      ): Alova2Method<Utils_response_array_system_menu, 'general.get_menus', Config>;
      /**
       * ---
       *
       * [POST] 创建菜单
       *
       * **path:** /menus
       *
       * ---
       *
       * **RequestBody**
       * ```ts
       * type RequestBody = {
       *   // 激活的菜单名
       *   activeMenu?: string
       *   buttons?: Array<{
       *     code?: string
       *     createTime?: string
       *     desc?: string
       *     id?: number
       *     updateTime?: string
       *   }>
       *   children?: Array<System_menu>
       *   component?: string
       *   constant?: boolean
       *   createTime?: string
       *   fixedIndexInTab?: number
       *   // 是否隐藏菜单
       *   hideInMenu?: boolean
       *   href?: string
       *   // [required]
       *   i18nKey: string
       *   icon?: string
       *   // [required]
       *   iconType: string
       *   id?: number
       *   keepAlive?: boolean
       *   localIcon?: string
       *   // [required]
       *   menuName: string
       *   // [required]
       *   menuType: string
       *   // 是否支持多标签
       *   multiTab?: boolean
       *   order?: number
       *   // 父菜单ID
       *   parentId?: number
       *   query?: Array<{
       *     id?: number
       *     key?: string
       *     menuId?: number
       *     value?: string
       *   }>
       *   // [required]
       *   routeName: string
       *   // [required]
       *   routePath: string
       *   status?: string
       *   updateTime?: string
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = {
       *   // [required]
       *   code: string
       *   // [required]
       *   data: Array<{
       *     // 激活的菜单名
       *     activeMenu?: string
       *     buttons?: Array<{
       *       code?: string
       *       createTime?: string
       *       desc?: string
       *       id?: number
       *       updateTime?: string
       *     }>
       *     children?: Array<System_menu>
       *     component?: string
       *     constant?: boolean
       *     createTime?: string
       *     fixedIndexInTab?: number
       *     // 是否隐藏菜单
       *     hideInMenu?: boolean
       *     href?: string
       *     // [required]
       *     i18nKey: string
       *     icon?: string
       *     // [required]
       *     iconType: string
       *     id?: number
       *     keepAlive?: boolean
       *     localIcon?: string
       *     // [required]
       *     menuName: string
       *     // [required]
       *     menuType: string
       *     // 是否支持多标签
       *     multiTab?: boolean
       *     order?: number
       *     // 父菜单ID
       *     parentId?: number
       *     query?: Array<{
       *       id?: number
       *       key?: string
       *       menuId?: number
       *       value?: string
       *     }>
       *     // [required]
       *     routeName: string
       *     // [required]
       *     routePath: string
       *     status?: string
       *     updateTime?: string
       *   }>
       *   // [required]
       *   msg: string
       * }
       * ```
       */
      post_menus<
        Config extends Alova2MethodConfig<Utils_response_array_system_menu> & {
          data: System_menu;
        }
      >(
        config: Config
      ): Alova2Method<Utils_response_array_system_menu, 'general.post_menus', Config>;
      /**
       * ---
       *
       * [POST] 批量删除菜单
       *
       * **path:** /menus/batchDelete
       *
       * ---
       *
       * **RequestBody**
       * ```ts
       * type RequestBody = {
       *   ids?: number[]
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = {
       *   // [required]
       *   code: string
       *   // [required]
       *   data: string
       *   // [required]
       *   msg: string
       * }
       * ```
       */
      post_menus_batchdelete<
        Config extends Alova2MethodConfig<Utils_response_string> & {
          data: {
            ids?: number[];
          };
        }
      >(
        config: Config
      ): Alova2Method<Utils_response_string, 'general.post_menus_batchdelete', Config>;
      /**
       * ---
       *
       * [GET] 获取常量菜单
       *
       * **path:** /menus/constant
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = {
       *   // [required]
       *   code: string
       *   // [required]
       *   data: Array<{
       *     // 激活的菜单名
       *     activeMenu?: string
       *     buttons?: Array<{
       *       code?: string
       *       createTime?: string
       *       desc?: string
       *       id?: number
       *       updateTime?: string
       *     }>
       *     children?: Array<System_menu>
       *     component?: string
       *     constant?: boolean
       *     createTime?: string
       *     fixedIndexInTab?: number
       *     // 是否隐藏菜单
       *     hideInMenu?: boolean
       *     href?: string
       *     // [required]
       *     i18nKey: string
       *     icon?: string
       *     // [required]
       *     iconType: string
       *     id?: number
       *     keepAlive?: boolean
       *     localIcon?: string
       *     // [required]
       *     menuName: string
       *     // [required]
       *     menuType: string
       *     // 是否支持多标签
       *     multiTab?: boolean
       *     order?: number
       *     // 父菜单ID
       *     parentId?: number
       *     query?: Array<{
       *       id?: number
       *       key?: string
       *       menuId?: number
       *       value?: string
       *     }>
       *     // [required]
       *     routeName: string
       *     // [required]
       *     routePath: string
       *     status?: string
       *     updateTime?: string
       *   }>
       *   // [required]
       *   msg: string
       * }
       * ```
       */
      get_menus_constant<Config extends Alova2MethodConfig<Utils_response_array_system_menu>>(
        config?: Config
      ): Alova2Method<Utils_response_array_system_menu, 'general.get_menus_constant', Config>;
      /**
       * ---
       *
       * [POST] 删除菜单
       *
       * **path:** /menus/delete
       *
       * ---
       *
       * **RequestBody**
       * ```ts
       * type RequestBody = {
       *   id?: number
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = {
       *   // [required]
       *   code: string
       *   // [required]
       *   data: string
       *   // [required]
       *   msg: string
       * }
       * ```
       */
      post_menus_delete<
        Config extends Alova2MethodConfig<Utils_response_string> & {
          data: {
            id?: number;
          };
        }
      >(
        config: Config
      ): Alova2Method<Utils_response_string, 'general.post_menus_delete', Config>;
      /**
       * ---
       *
       * [GET] 获取角色菜单
       *
       * **path:** /menus/role
       *
       * ---
       *
       * **Query Parameters**
       * ```ts
       * type QueryParameters = {
       *   // 角色ID
       *   // [required]
       *   roleId: number
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = {
       *   // [required]
       *   code: string
       *   // [required]
       *   data: Array<{
       *     // 激活的菜单名
       *     activeMenu?: string
       *     buttons?: Array<{
       *       code?: string
       *       createTime?: string
       *       desc?: string
       *       id?: number
       *       updateTime?: string
       *     }>
       *     children?: Array<System_menu>
       *     component?: string
       *     constant?: boolean
       *     createTime?: string
       *     fixedIndexInTab?: number
       *     // 是否隐藏菜单
       *     hideInMenu?: boolean
       *     href?: string
       *     // [required]
       *     i18nKey: string
       *     icon?: string
       *     // [required]
       *     iconType: string
       *     id?: number
       *     keepAlive?: boolean
       *     localIcon?: string
       *     // [required]
       *     menuName: string
       *     // [required]
       *     menuType: string
       *     // 是否支持多标签
       *     multiTab?: boolean
       *     order?: number
       *     // 父菜单ID
       *     parentId?: number
       *     query?: Array<{
       *       id?: number
       *       key?: string
       *       menuId?: number
       *       value?: string
       *     }>
       *     // [required]
       *     routeName: string
       *     // [required]
       *     routePath: string
       *     status?: string
       *     updateTime?: string
       *   }>
       *   // [required]
       *   msg: string
       * }
       * ```
       */
      get_menus_role<
        Config extends Alova2MethodConfig<Utils_response_array_system_menu> & {
          params: {
            /**
             * 角色ID
             * [required]
             */
            roleId: number;
          };
        }
      >(
        config: Config
      ): Alova2Method<Utils_response_array_system_menu, 'general.get_menus_role', Config>;
      /**
       * ---
       *
       * [POST] 更新菜单
       *
       * **path:** /menus/update
       *
       * ---
       *
       * **RequestBody**
       * ```ts
       * type RequestBody = {
       *   // 激活的菜单名
       *   activeMenu?: string
       *   buttons?: Array<{
       *     code?: string
       *     createTime?: string
       *     desc?: string
       *     id?: number
       *     updateTime?: string
       *   }>
       *   children?: Array<System_menu>
       *   component?: string
       *   constant?: boolean
       *   createTime?: string
       *   fixedIndexInTab?: number
       *   // 是否隐藏菜单
       *   hideInMenu?: boolean
       *   href?: string
       *   // [required]
       *   i18nKey: string
       *   icon?: string
       *   // [required]
       *   iconType: string
       *   id?: number
       *   keepAlive?: boolean
       *   localIcon?: string
       *   // [required]
       *   menuName: string
       *   // [required]
       *   menuType: string
       *   // 是否支持多标签
       *   multiTab?: boolean
       *   order?: number
       *   // 父菜单ID
       *   parentId?: number
       *   query?: Array<{
       *     id?: number
       *     key?: string
       *     menuId?: number
       *     value?: string
       *   }>
       *   // [required]
       *   routeName: string
       *   // [required]
       *   routePath: string
       *   status?: string
       *   updateTime?: string
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = {
       *   // [required]
       *   code: string
       *   // [required]
       *   data: Array<{
       *     // 激活的菜单名
       *     activeMenu?: string
       *     buttons?: Array<{
       *       code?: string
       *       createTime?: string
       *       desc?: string
       *       id?: number
       *       updateTime?: string
       *     }>
       *     children?: Array<System_menu>
       *     component?: string
       *     constant?: boolean
       *     createTime?: string
       *     fixedIndexInTab?: number
       *     // 是否隐藏菜单
       *     hideInMenu?: boolean
       *     href?: string
       *     // [required]
       *     i18nKey: string
       *     icon?: string
       *     // [required]
       *     iconType: string
       *     id?: number
       *     keepAlive?: boolean
       *     localIcon?: string
       *     // [required]
       *     menuName: string
       *     // [required]
       *     menuType: string
       *     // 是否支持多标签
       *     multiTab?: boolean
       *     order?: number
       *     // 父菜单ID
       *     parentId?: number
       *     query?: Array<{
       *       id?: number
       *       key?: string
       *       menuId?: number
       *       value?: string
       *     }>
       *     // [required]
       *     routeName: string
       *     // [required]
       *     routePath: string
       *     status?: string
       *     updateTime?: string
       *   }>
       *   // [required]
       *   msg: string
       * }
       * ```
       */
      post_menus_update<
        Config extends Alova2MethodConfig<Utils_response_array_system_menu> & {
          data: System_menu;
        }
      >(
        config: Config
      ): Alova2Method<Utils_response_array_system_menu, 'general.post_menus_update', Config>;
      /**
       * ---
       *
       * [GET] 获取用户菜单
       *
       * **path:** /menus/user
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = {
       *   // [required]
       *   code: string
       *   // [required]
       *   data: Array<{
       *     // 激活的菜单名
       *     activeMenu?: string
       *     buttons?: Array<{
       *       code?: string
       *       createTime?: string
       *       desc?: string
       *       id?: number
       *       updateTime?: string
       *     }>
       *     children?: Array<System_menu>
       *     component?: string
       *     constant?: boolean
       *     createTime?: string
       *     fixedIndexInTab?: number
       *     // 是否隐藏菜单
       *     hideInMenu?: boolean
       *     href?: string
       *     // [required]
       *     i18nKey: string
       *     icon?: string
       *     // [required]
       *     iconType: string
       *     id?: number
       *     keepAlive?: boolean
       *     localIcon?: string
       *     // [required]
       *     menuName: string
       *     // [required]
       *     menuType: string
       *     // 是否支持多标签
       *     multiTab?: boolean
       *     order?: number
       *     // 父菜单ID
       *     parentId?: number
       *     query?: Array<{
       *       id?: number
       *       key?: string
       *       menuId?: number
       *       value?: string
       *     }>
       *     // [required]
       *     routeName: string
       *     // [required]
       *     routePath: string
       *     status?: string
       *     updateTime?: string
       *   }>
       *   // [required]
       *   msg: string
       * }
       * ```
       */
      get_menus_user<Config extends Alova2MethodConfig<Utils_response_array_system_menu>>(
        config?: Config
      ): Alova2Method<Utils_response_array_system_menu, 'general.get_menus_user', Config>;
      /**
       * ---
       *
       * [GET] 获取分页角色列表
       *
       * **path:** /roles
       *
       * ---
       *
       * **Query Parameters**
       * ```ts
       * type QueryParameters = {
       *   // 页码
       *   current?: number
       *   // 每页条数
       *   size?: number
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = {
       *   // [required]
       *   code: string
       *   // [required]
       *   data: {
       *     // [required]
       *     current: number
       *     // [required]
       *     records: Array<{
       *       buttons?: Array<{
       *         code?: string
       *         createTime?: string
       *         desc?: string
       *         id?: number
       *         updateTime?: string
       *       }>
       *       createTime?: string
       *       id?: number
       *       menu?: Array<{
       *         // 激活的菜单名
       *         activeMenu?: string
       *         buttons?: Array<{
       *           code?: string
       *           createTime?: string
       *           desc?: string
       *           id?: number
       *           updateTime?: string
       *         }>
       *         children?: Array<System_menu>
       *         component?: string
       *         constant?: boolean
       *         createTime?: string
       *         fixedIndexInTab?: number
       *         // 是否隐藏菜单
       *         hideInMenu?: boolean
       *         href?: string
       *         // [required]
       *         i18nKey: string
       *         icon?: string
       *         // [required]
       *         iconType: string
       *         id?: number
       *         keepAlive?: boolean
       *         localIcon?: string
       *         // [required]
       *         menuName: string
       *         // [required]
       *         menuType: string
       *         // 是否支持多标签
       *         multiTab?: boolean
       *         order?: number
       *         // 父菜单ID
       *         parentId?: number
       *         query?: Array<{
       *           id?: number
       *           key?: string
       *           menuId?: number
       *           value?: string
       *         }>
       *         // [required]
       *         routeName: string
       *         // [required]
       *         routePath: string
       *         status?: string
       *         updateTime?: string
       *       }>
       *       roleDesc?: string
       *       roleName?: string
       *       updateTime?: string
       *     }>
       *     // [required]
       *     size: number
       *     // [required]
       *     total: number
       *   }
       *   // [required]
       *   msg: string
       * }
       * ```
       */
      get_roles<
        Config extends Alova2MethodConfig<Utils_response_utils_pagination_system_role> & {
          params: {
            /**
             * 页码
             */
            current?: number;
            /**
             * 每页条数
             */
            size?: number;
          };
        }
      >(
        config: Config
      ): Alova2Method<Utils_response_utils_pagination_system_role, 'general.get_roles', Config>;
      /**
       * ---
       *
       * [POST] 创建角色
       *
       * **path:** /roles
       *
       * ---
       *
       * **RequestBody**
       * ```ts
       * type RequestBody = {
       *   buttons?: Array<{
       *     code?: string
       *     createTime?: string
       *     desc?: string
       *     id?: number
       *     updateTime?: string
       *   }>
       *   createTime?: string
       *   id?: number
       *   menu?: Array<{
       *     // 激活的菜单名
       *     activeMenu?: string
       *     buttons?: Array<{
       *       code?: string
       *       createTime?: string
       *       desc?: string
       *       id?: number
       *       updateTime?: string
       *     }>
       *     children?: Array<System_menu>
       *     component?: string
       *     constant?: boolean
       *     createTime?: string
       *     fixedIndexInTab?: number
       *     // 是否隐藏菜单
       *     hideInMenu?: boolean
       *     href?: string
       *     // [required]
       *     i18nKey: string
       *     icon?: string
       *     // [required]
       *     iconType: string
       *     id?: number
       *     keepAlive?: boolean
       *     localIcon?: string
       *     // [required]
       *     menuName: string
       *     // [required]
       *     menuType: string
       *     // 是否支持多标签
       *     multiTab?: boolean
       *     order?: number
       *     // 父菜单ID
       *     parentId?: number
       *     query?: Array<{
       *       id?: number
       *       key?: string
       *       menuId?: number
       *       value?: string
       *     }>
       *     // [required]
       *     routeName: string
       *     // [required]
       *     routePath: string
       *     status?: string
       *     updateTime?: string
       *   }>
       *   roleDesc?: string
       *   roleName?: string
       *   updateTime?: string
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = {
       *   // [required]
       *   code: string
       *   // [required]
       *   data: {
       *     buttons?: Array<{
       *       code?: string
       *       createTime?: string
       *       desc?: string
       *       id?: number
       *       updateTime?: string
       *     }>
       *     createTime?: string
       *     id?: number
       *     menu?: Array<{
       *       // 激活的菜单名
       *       activeMenu?: string
       *       buttons?: Array<{
       *         code?: string
       *         createTime?: string
       *         desc?: string
       *         id?: number
       *         updateTime?: string
       *       }>
       *       children?: Array<System_menu>
       *       component?: string
       *       constant?: boolean
       *       createTime?: string
       *       fixedIndexInTab?: number
       *       // 是否隐藏菜单
       *       hideInMenu?: boolean
       *       href?: string
       *       // [required]
       *       i18nKey: string
       *       icon?: string
       *       // [required]
       *       iconType: string
       *       id?: number
       *       keepAlive?: boolean
       *       localIcon?: string
       *       // [required]
       *       menuName: string
       *       // [required]
       *       menuType: string
       *       // 是否支持多标签
       *       multiTab?: boolean
       *       order?: number
       *       // 父菜单ID
       *       parentId?: number
       *       query?: Array<{
       *         id?: number
       *         key?: string
       *         menuId?: number
       *         value?: string
       *       }>
       *       // [required]
       *       routeName: string
       *       // [required]
       *       routePath: string
       *       status?: string
       *       updateTime?: string
       *     }>
       *     roleDesc?: string
       *     roleName?: string
       *     updateTime?: string
       *   }
       *   // [required]
       *   msg: string
       * }
       * ```
       */
      post_roles<
        Config extends Alova2MethodConfig<Utils_response_system_role> & {
          data: System_role;
        }
      >(
        config: Config
      ): Alova2Method<Utils_response_system_role, 'general.post_roles', Config>;
      /**
       * ---
       *
       * [GET] 获取所有角色
       *
       * **path:** /roles/all
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = {
       *   // [required]
       *   code: string
       *   // [required]
       *   data: Array<{
       *     buttons?: Array<{
       *       code?: string
       *       createTime?: string
       *       desc?: string
       *       id?: number
       *       updateTime?: string
       *     }>
       *     createTime?: string
       *     id?: number
       *     menu?: Array<{
       *       // 激活的菜单名
       *       activeMenu?: string
       *       buttons?: Array<{
       *         code?: string
       *         createTime?: string
       *         desc?: string
       *         id?: number
       *         updateTime?: string
       *       }>
       *       children?: Array<System_menu>
       *       component?: string
       *       constant?: boolean
       *       createTime?: string
       *       fixedIndexInTab?: number
       *       // 是否隐藏菜单
       *       hideInMenu?: boolean
       *       href?: string
       *       // [required]
       *       i18nKey: string
       *       icon?: string
       *       // [required]
       *       iconType: string
       *       id?: number
       *       keepAlive?: boolean
       *       localIcon?: string
       *       // [required]
       *       menuName: string
       *       // [required]
       *       menuType: string
       *       // 是否支持多标签
       *       multiTab?: boolean
       *       order?: number
       *       // 父菜单ID
       *       parentId?: number
       *       query?: Array<{
       *         id?: number
       *         key?: string
       *         menuId?: number
       *         value?: string
       *       }>
       *       // [required]
       *       routeName: string
       *       // [required]
       *       routePath: string
       *       status?: string
       *       updateTime?: string
       *     }>
       *     roleDesc?: string
       *     roleName?: string
       *     updateTime?: string
       *   }>
       *   // [required]
       *   msg: string
       * }
       * ```
       */
      get_roles_all<Config extends Alova2MethodConfig<Utils_response_array_system_role>>(
        config?: Config
      ): Alova2Method<Utils_response_array_system_role, 'general.get_roles_all', Config>;
      /**
       * ---
       *
       * [POST] 批量删除角色
       *
       * **path:** /roles/batchDelete
       *
       * ---
       *
       * **RequestBody**
       * ```ts
       * type RequestBody = {
       *   ids?: number[]
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = {
       *   // [required]
       *   code: string
       *   // [required]
       *   data: string
       *   // [required]
       *   msg: string
       * }
       * ```
       */
      post_roles_batchdelete<
        Config extends Alova2MethodConfig<Utils_response_string> & {
          data: {
            ids?: number[];
          };
        }
      >(
        config: Config
      ): Alova2Method<Utils_response_string, 'general.post_roles_batchdelete', Config>;
      /**
       * ---
       *
       * [POST] 更新角色按钮权限
       *
       * **path:** /roles/buttons
       *
       * ---
       *
       * **RequestBody**
       * ```ts
       * type RequestBody = {
       *   buttonIds?: number[]
       *   roleId?: number
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = {
       *   // [required]
       *   code: string
       *   // [required]
       *   data: string
       *   // [required]
       *   msg: string
       * }
       * ```
       */
      post_roles_buttons<
        Config extends Alova2MethodConfig<Utils_response_string> & {
          data: {
            buttonIds?: number[];
            roleId?: number;
          };
        }
      >(
        config: Config
      ): Alova2Method<Utils_response_string, 'general.post_roles_buttons', Config>;
      /**
       * ---
       *
       * [POST] 删除角色
       *
       * **path:** /roles/delete
       *
       * ---
       *
       * **RequestBody**
       * ```ts
       * type RequestBody = {
       *   id?: number
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = {
       *   // [required]
       *   code: string
       *   // [required]
       *   data: string
       *   // [required]
       *   msg: string
       * }
       * ```
       */
      post_roles_delete<
        Config extends Alova2MethodConfig<Utils_response_string> & {
          data: {
            id?: number;
          };
        }
      >(
        config: Config
      ): Alova2Method<Utils_response_string, 'general.post_roles_delete', Config>;
      /**
       * ---
       *
       * [POST] 更新角色菜单
       *
       * **path:** /roles/menus
       *
       * ---
       *
       * **RequestBody**
       * ```ts
       * type RequestBody = {
       *   menuIds?: number[]
       *   roleId?: number
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = {
       *   // [required]
       *   code: string
       *   // [required]
       *   data: string
       *   // [required]
       *   msg: string
       * }
       * ```
       */
      post_roles_menus<
        Config extends Alova2MethodConfig<Utils_response_string> & {
          data: {
            menuIds?: number[];
            roleId?: number;
          };
        }
      >(
        config: Config
      ): Alova2Method<Utils_response_string, 'general.post_roles_menus', Config>;
      /**
       * ---
       *
       * [POST] 更新角色
       *
       * **path:** /roles/update
       *
       * ---
       *
       * **RequestBody**
       * ```ts
       * type RequestBody = {
       *   buttons?: Array<{
       *     code?: string
       *     createTime?: string
       *     desc?: string
       *     id?: number
       *     updateTime?: string
       *   }>
       *   createTime?: string
       *   id?: number
       *   menu?: Array<{
       *     // 激活的菜单名
       *     activeMenu?: string
       *     buttons?: Array<{
       *       code?: string
       *       createTime?: string
       *       desc?: string
       *       id?: number
       *       updateTime?: string
       *     }>
       *     children?: Array<System_menu>
       *     component?: string
       *     constant?: boolean
       *     createTime?: string
       *     fixedIndexInTab?: number
       *     // 是否隐藏菜单
       *     hideInMenu?: boolean
       *     href?: string
       *     // [required]
       *     i18nKey: string
       *     icon?: string
       *     // [required]
       *     iconType: string
       *     id?: number
       *     keepAlive?: boolean
       *     localIcon?: string
       *     // [required]
       *     menuName: string
       *     // [required]
       *     menuType: string
       *     // 是否支持多标签
       *     multiTab?: boolean
       *     order?: number
       *     // 父菜单ID
       *     parentId?: number
       *     query?: Array<{
       *       id?: number
       *       key?: string
       *       menuId?: number
       *       value?: string
       *     }>
       *     // [required]
       *     routeName: string
       *     // [required]
       *     routePath: string
       *     status?: string
       *     updateTime?: string
       *   }>
       *   roleDesc?: string
       *   roleName?: string
       *   updateTime?: string
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = {
       *   // [required]
       *   code: string
       *   // [required]
       *   data: string
       *   // [required]
       *   msg: string
       * }
       * ```
       */
      post_roles_update<
        Config extends Alova2MethodConfig<Utils_response_string> & {
          data: System_role;
        }
      >(
        config: Config
      ): Alova2Method<Utils_response_string, 'general.post_roles_update', Config>;
      /**
       * ---
       *
       * [GET] 获取用户列表
       *
       * **path:** /users
       *
       * ---
       *
       * **Query Parameters**
       * ```ts
       * type QueryParameters = {
       *   // 页码
       *   current?: number
       *   // 每页条数
       *   size?: number
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = {
       *   // [required]
       *   code: string
       *   // [required]
       *   data: {
       *     // [required]
       *     current: number
       *     // [required]
       *     records: Array<{
       *       createTime?: string
       *       id?: number
       *       password?: string
       *       roles?: Array<{
       *         buttons?: Array<{
       *           code?: string
       *           createTime?: string
       *           desc?: string
       *           id?: number
       *           updateTime?: string
       *         }>
       *         createTime?: string
       *         id?: number
       *         menu?: Array<{
       *           // 激活的菜单名
       *           activeMenu?: string
       *           buttons?: Array<{
       *             code?: string
       *             createTime?: string
       *             desc?: string
       *             id?: number
       *             updateTime?: string
       *           }>
       *           children?: Array<System_menu>
       *           component?: string
       *           constant?: boolean
       *           createTime?: string
       *           fixedIndexInTab?: number
       *           // 是否隐藏菜单
       *           hideInMenu?: boolean
       *           href?: string
       *           // [required]
       *           i18nKey: string
       *           icon?: string
       *           // [required]
       *           iconType: string
       *           id?: number
       *           keepAlive?: boolean
       *           localIcon?: string
       *           // [required]
       *           menuName: string
       *           // [required]
       *           menuType: string
       *           // 是否支持多标签
       *           multiTab?: boolean
       *           order?: number
       *           // 父菜单ID
       *           parentId?: number
       *           query?: Array<{
       *             id?: number
       *             key?: string
       *             menuId?: number
       *             value?: string
       *           }>
       *           // [required]
       *           routeName: string
       *           // [required]
       *           routePath: string
       *           status?: string
       *           updateTime?: string
       *         }>
       *         roleDesc?: string
       *         roleName?: string
       *         updateTime?: string
       *       }>
       *       updateTime?: string
       *       userName?: string
       *     }>
       *     // [required]
       *     size: number
       *     // [required]
       *     total: number
       *   }
       *   // [required]
       *   msg: string
       * }
       * ```
       */
      get_users<
        Config extends Alova2MethodConfig<Utils_response_utils_pagination_system_user> & {
          params: {
            /**
             * 页码
             */
            current?: number;
            /**
             * 每页条数
             */
            size?: number;
          };
        }
      >(
        config: Config
      ): Alova2Method<Utils_response_utils_pagination_system_user, 'general.get_users', Config>;
      /**
       * ---
       *
       * [POST] 创建用户
       *
       * **path:** /users
       *
       * ---
       *
       * **RequestBody**
       * ```ts
       * type RequestBody = {
       *   createTime?: string
       *   id?: number
       *   password?: string
       *   roles?: Array<{
       *     buttons?: Array<{
       *       code?: string
       *       createTime?: string
       *       desc?: string
       *       id?: number
       *       updateTime?: string
       *     }>
       *     createTime?: string
       *     id?: number
       *     menu?: Array<{
       *       // 激活的菜单名
       *       activeMenu?: string
       *       buttons?: Array<{
       *         code?: string
       *         createTime?: string
       *         desc?: string
       *         id?: number
       *         updateTime?: string
       *       }>
       *       children?: Array<System_menu>
       *       component?: string
       *       constant?: boolean
       *       createTime?: string
       *       fixedIndexInTab?: number
       *       // 是否隐藏菜单
       *       hideInMenu?: boolean
       *       href?: string
       *       // [required]
       *       i18nKey: string
       *       icon?: string
       *       // [required]
       *       iconType: string
       *       id?: number
       *       keepAlive?: boolean
       *       localIcon?: string
       *       // [required]
       *       menuName: string
       *       // [required]
       *       menuType: string
       *       // 是否支持多标签
       *       multiTab?: boolean
       *       order?: number
       *       // 父菜单ID
       *       parentId?: number
       *       query?: Array<{
       *         id?: number
       *         key?: string
       *         menuId?: number
       *         value?: string
       *       }>
       *       // [required]
       *       routeName: string
       *       // [required]
       *       routePath: string
       *       status?: string
       *       updateTime?: string
       *     }>
       *     roleDesc?: string
       *     roleName?: string
       *     updateTime?: string
       *   }>
       *   updateTime?: string
       *   userName?: string
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = {
       *   // [required]
       *   code: string
       *   // [required]
       *   data: {
       *     createTime?: string
       *     id?: number
       *     password?: string
       *     roles?: Array<{
       *       buttons?: Array<{
       *         code?: string
       *         createTime?: string
       *         desc?: string
       *         id?: number
       *         updateTime?: string
       *       }>
       *       createTime?: string
       *       id?: number
       *       menu?: Array<{
       *         // 激活的菜单名
       *         activeMenu?: string
       *         buttons?: Array<{
       *           code?: string
       *           createTime?: string
       *           desc?: string
       *           id?: number
       *           updateTime?: string
       *         }>
       *         children?: Array<System_menu>
       *         component?: string
       *         constant?: boolean
       *         createTime?: string
       *         fixedIndexInTab?: number
       *         // 是否隐藏菜单
       *         hideInMenu?: boolean
       *         href?: string
       *         // [required]
       *         i18nKey: string
       *         icon?: string
       *         // [required]
       *         iconType: string
       *         id?: number
       *         keepAlive?: boolean
       *         localIcon?: string
       *         // [required]
       *         menuName: string
       *         // [required]
       *         menuType: string
       *         // 是否支持多标签
       *         multiTab?: boolean
       *         order?: number
       *         // 父菜单ID
       *         parentId?: number
       *         query?: Array<{
       *           id?: number
       *           key?: string
       *           menuId?: number
       *           value?: string
       *         }>
       *         // [required]
       *         routeName: string
       *         // [required]
       *         routePath: string
       *         status?: string
       *         updateTime?: string
       *       }>
       *       roleDesc?: string
       *       roleName?: string
       *       updateTime?: string
       *     }>
       *     updateTime?: string
       *     userName?: string
       *   }
       *   // [required]
       *   msg: string
       * }
       * ```
       */
      post_users<
        Config extends Alova2MethodConfig<Utils_response_system_user> & {
          data: System_user;
        }
      >(
        config: Config
      ): Alova2Method<Utils_response_system_user, 'general.post_users', Config>;
      /**
       * ---
       *
       * [POST] 批量删除用户
       *
       * **path:** /users/batchDelete
       *
       * ---
       *
       * **RequestBody**
       * ```ts
       * type RequestBody = number[]
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = {
       *   // [required]
       *   code: string
       *   // [required]
       *   data: string
       *   // [required]
       *   msg: string
       * }
       * ```
       */
      post_users_batchdelete<
        Config extends Alova2MethodConfig<Utils_response_string> & {
          data: number[];
        }
      >(
        config: Config
      ): Alova2Method<Utils_response_string, 'general.post_users_batchdelete', Config>;
      /**
       * ---
       *
       * [GET] 检查用户名是否存在
       *
       * **path:** /users/checkUsername
       *
       * ---
       *
       * **Query Parameters**
       * ```ts
       * type QueryParameters = {
       *   // 用户名
       *   // [required]
       *   userName: string
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = {
       *   // [required]
       *   code: string
       *   // [required]
       *   data: {
       *     exists?: boolean
       *   }
       *   // [required]
       *   msg: string
       * }
       * ```
       */
      get_users_checkusername<
        Config extends Alova2MethodConfig<Utils_response_utils_existsresult> & {
          params: {
            /**
             * 用户名
             * [required]
             */
            userName: string;
          };
        }
      >(
        config: Config
      ): Alova2Method<Utils_response_utils_existsresult, 'general.get_users_checkusername', Config>;
      /**
       * ---
       *
       * [POST] 删除用户
       *
       * **path:** /users/delete
       *
       * ---
       *
       * **RequestBody**
       * ```ts
       * type RequestBody = {
       *   createTime?: string
       *   id?: number
       *   password?: string
       *   roles?: Array<{
       *     buttons?: Array<{
       *       code?: string
       *       createTime?: string
       *       desc?: string
       *       id?: number
       *       updateTime?: string
       *     }>
       *     createTime?: string
       *     id?: number
       *     menu?: Array<{
       *       // 激活的菜单名
       *       activeMenu?: string
       *       buttons?: Array<{
       *         code?: string
       *         createTime?: string
       *         desc?: string
       *         id?: number
       *         updateTime?: string
       *       }>
       *       children?: Array<System_menu>
       *       component?: string
       *       constant?: boolean
       *       createTime?: string
       *       fixedIndexInTab?: number
       *       // 是否隐藏菜单
       *       hideInMenu?: boolean
       *       href?: string
       *       // [required]
       *       i18nKey: string
       *       icon?: string
       *       // [required]
       *       iconType: string
       *       id?: number
       *       keepAlive?: boolean
       *       localIcon?: string
       *       // [required]
       *       menuName: string
       *       // [required]
       *       menuType: string
       *       // 是否支持多标签
       *       multiTab?: boolean
       *       order?: number
       *       // 父菜单ID
       *       parentId?: number
       *       query?: Array<{
       *         id?: number
       *         key?: string
       *         menuId?: number
       *         value?: string
       *       }>
       *       // [required]
       *       routeName: string
       *       // [required]
       *       routePath: string
       *       status?: string
       *       updateTime?: string
       *     }>
       *     roleDesc?: string
       *     roleName?: string
       *     updateTime?: string
       *   }>
       *   updateTime?: string
       *   userName?: string
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = {
       *   // [required]
       *   code: string
       *   // [required]
       *   data: string
       *   // [required]
       *   msg: string
       * }
       * ```
       */
      post_users_delete<
        Config extends Alova2MethodConfig<Utils_response_string> & {
          data: System_user;
        }
      >(
        config: Config
      ): Alova2Method<Utils_response_string, 'general.post_users_delete', Config>;
      /**
       * ---
       *
       * [POST] 更新用户密码
       *
       * **path:** /users/password
       *
       * ---
       *
       * **RequestBody**
       * ```ts
       * type RequestBody = {
       *   id?: number
       *   password?: string
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = {
       *   // [required]
       *   code: string
       *   // [required]
       *   data: string
       *   // [required]
       *   msg: string
       * }
       * ```
       */
      post_users_password<
        Config extends Alova2MethodConfig<Utils_response_string> & {
          data: {
            id?: number;
            password?: string;
          };
        }
      >(
        config: Config
      ): Alova2Method<Utils_response_string, 'general.post_users_password', Config>;
      /**
       * ---
       *
       * [GET] 获取用户角色
       *
       * **path:** /users/roles
       *
       * ---
       *
       * **Query Parameters**
       * ```ts
       * type QueryParameters = {
       *   // 用户ID
       *   // [required]
       *   id: number
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = {
       *   // [required]
       *   code: string
       *   // [required]
       *   data: Array<{
       *     buttons?: Array<{
       *       code?: string
       *       createTime?: string
       *       desc?: string
       *       id?: number
       *       updateTime?: string
       *     }>
       *     createTime?: string
       *     id?: number
       *     menu?: Array<{
       *       // 激活的菜单名
       *       activeMenu?: string
       *       buttons?: Array<{
       *         code?: string
       *         createTime?: string
       *         desc?: string
       *         id?: number
       *         updateTime?: string
       *       }>
       *       children?: Array<System_menu>
       *       component?: string
       *       constant?: boolean
       *       createTime?: string
       *       fixedIndexInTab?: number
       *       // 是否隐藏菜单
       *       hideInMenu?: boolean
       *       href?: string
       *       // [required]
       *       i18nKey: string
       *       icon?: string
       *       // [required]
       *       iconType: string
       *       id?: number
       *       keepAlive?: boolean
       *       localIcon?: string
       *       // [required]
       *       menuName: string
       *       // [required]
       *       menuType: string
       *       // 是否支持多标签
       *       multiTab?: boolean
       *       order?: number
       *       // 父菜单ID
       *       parentId?: number
       *       query?: Array<{
       *         id?: number
       *         key?: string
       *         menuId?: number
       *         value?: string
       *       }>
       *       // [required]
       *       routeName: string
       *       // [required]
       *       routePath: string
       *       status?: string
       *       updateTime?: string
       *     }>
       *     roleDesc?: string
       *     roleName?: string
       *     updateTime?: string
       *   }>
       *   // [required]
       *   msg: string
       * }
       * ```
       */
      get_users_roles<
        Config extends Alova2MethodConfig<Utils_response_array_system_role> & {
          params: {
            /**
             * 用户ID
             * [required]
             */
            id: number;
          };
        }
      >(
        config: Config
      ): Alova2Method<Utils_response_array_system_role, 'general.get_users_roles', Config>;
      /**
       * ---
       *
       * [POST] 更新用户角色
       *
       * **path:** /users/roles
       *
       * ---
       *
       * **RequestBody**
       * ```ts
       * type RequestBody = {
       *   id?: number
       *   roleIds?: number[]
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = {
       *   // [required]
       *   code: string
       *   // [required]
       *   data: string
       *   // [required]
       *   msg: string
       * }
       * ```
       */
      post_users_roles<
        Config extends Alova2MethodConfig<Utils_response_string> & {
          data: {
            id?: number;
            roleIds?: number[];
          };
        }
      >(
        config: Config
      ): Alova2Method<Utils_response_string, 'general.post_users_roles', Config>;
    };
  }

  var Apis: Apis;
}
